services:
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./test.txt:/test.txt
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret

volumes:
  mysql-data:
